FurnitureStore/ViewModels/ShoppingCartViewModel.cs
using FurnitureStore.Models;
using System.Collections.Generic;

namespace FurnitureStore.ViewModels
{
    public class ShoppingCartViewModel
    {
        // Proizvodi u korpi
        public List<ShoppingCartProduct> CartProducts { get; set; }

        // Ukupna cena za sve proizvode u korpi sa porezom
        public decimal BillTotalPriceWithTax { get; set; }

        // Ukupna cena za sve proizvode u korpi bez poreza
        public decimal BillTotalPriceWithOutTax { get; set; }
        public ShoppingCartViewModel()
        {
            CartProducts = new List<ShoppingCartProduct>();
        }
    }
}

FurnitureStore/Controllers/ShoppingController.cs
using FurnitureStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System;
using Microsoft.AspNet.Identity;
using FurnitureStore.ViewModels;

namespace FurnitureStore.Controllers
{
    public class ShoppingController : Controller
    {
        #region Konekcija ka bazi
        private readonly FurnitureStoreDbContext _context;
        private ShoppingCartViewModel cart;
        public ShoppingController()
        {
            _context = new FurnitureStoreDbContext();
            cart = new ShoppingCartViewModel();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        #endregion

        // GET: /Shopping/GetCartProducts
        [HttpGet]
        public ActionResult GetCartProducts()
        {
            if (Session["CartProducts"] != null)
            {
                var cartProducts = (Session["CartProducts"] as ShoppingCartViewModel).CartProducts;

                var query = from c in cartProducts
                            select new
                            {
                                ProductName = c.ProductName,
                                ShopName = c.ShopName,
                                UnitPrice = c.UnitPrice,
                                Add = c.ProductId,
                                Quantity = c.Quantity,
                                Remove = c.ProductId,
                                TotalPrice = c.TotalPrice,
                                ProductId = c.ProductId,
                                BillTotal = cartProducts.Sum(x => x.TotalPrice)
                            };


                return Json(new { data = query }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { data = "" }, JsonRequestBehavior.AllowGet);
        }

        // GET: /Shoping/ShoppingCart
        [HttpGet]
        public ActionResult ShoppingCart()
        {
            cart = Session["CartProducts"] as ShoppingCartViewModel;

            return View(cart);
        }

        // POST: /Shoping/AddToCart/1
        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            var productDb = _context.Products.Include(x => x.ProductType).Single(x => x.Id == id);
            ShoppingCartProduct cartProduct = new ShoppingCartProduct();

            // Ako korpa nije prazna dodeli cartProducts listi vrednost Session["CartProducts"]
            // koji u sebi ima sve do sada dodate proizvode
            if (Session["CartCounter"] != null)
            {
                cart = Session["CartProducts"] as ShoppingCartViewModel;
            }

            // Proveri da li proizvoda koji kupac hoce da kupi ima na stanju
            if (productDb.Quantity > 0)
            {
                // Ako u korpi vec ima odabranog proizvoda
                if (cart.CartProducts.Any(product => product.ProductId == id))
                {
                    // i kolicina koju kupac hoce da kupi je manja od one u zalihama
                    // samo dodaj na kolicinu jedan i izracunaj ukupnu cenu
                    if (cart.CartProducts.Single(x => x.ProductId == id).Quantity < productDb.Quantity)
                    {
                        cartProduct = cart.CartProducts.Single(x => x.ProductId == id);
                        cartProduct.Quantity += 1;
                        cartProduct.TotalPrice = cartProduct.Quantity * cartProduct.UnitPrice;

                        cart.BillTotalPriceWithOutTax += cartProduct.UnitPrice;
                        cart.BillTotalPriceWithTax = ((ConstantValues.Tax / 100) * cart.BillTotalPriceWithOutTax) + cart.BillTotalPriceWithOutTax;
                    }
                    // u suprotnom vrati poruku da nema na stanju
                    else
                    {
                        return Json(new { success = false, message = "Nema na stanju", counter = cart.CartProducts.Count }, JsonRequestBehavior.AllowGet);
                    }
                }
                // Ako proizvod nije vec dodat u korpu napravi novi ShoppingCartProduct i dodaj ga u korpu
                else
                {
                    cartProduct.ProductId = productDb.Id;
                    cartProduct.ProductName = productDb.ProductName;
                    cartProduct.ProductTypeName = productDb.ProductType.TypeName;
                    cartProduct.UnitPrice = productDb.Price;
                    cartProduct.TotalPrice = productDb.Price;
                    cartProduct.Quantity = 1;
                    cartProduct.ShopName = productDb.Shop.ShopName;

                    cart.CartProducts.Add(cartProduct);

                    cart.BillTotalPriceWithOutTax += cartProduct.UnitPrice;
                    cart.BillTotalPriceWithTax = ((ConstantValues.Tax / 100) * cart.BillTotalPriceWithOutTax) + cart.BillTotalPriceWithOutTax;
                }
            }
            // Ako proizvoda nema na stanju a korisnik hoce da ga dodao u korpu vrati mu poruku
            // da proizvoda nema na stanju
            else
            {
                return Json(new { success = false, message = "Nema na stanju", counter = cart.CartProducts.Count }, JsonRequestBehavior.AllowGet);
            }

            // Session CartCounter koristimo da bi kupac imao uvida koliko vrsta proizvoda ima u korpi
            Session["CartCounter"] = cart.CartProducts.Count;
            // Session CartProducts koristimo da bi sacuvali sve proizvode koje je kupac dodao u korpu
            Session["CartProducts"] = cart;

            return Json(new 
            { 
                success = true, 
                message = "Dodato u korpu", 
                counter = cart.CartProducts.Count, 
                total = cart.BillTotalPriceWithOutTax,
                totalTax = cart.BillTotalPriceWithTax
            }, JsonRequestBehavior.AllowGet);
        }

        // POST: /Shopping/RemoveFromCart/1
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            cart = Session["CartProducts"] as ShoppingCartViewModel;

            // Ako korpa nije null
            if (cart.CartProducts != null)
            {
                // Uzmi proizvode u korpi
                var cartProducts = cart.CartProducts;

                // Proveri da li ima nesto u njoj
                if (cartProducts.Any())
                {
                    // Pronadji proizvod sa prosledjenim id-jem
                    var cartProduct = cartProducts.FirstOrDefault(x => x.ProductId == id);
                    // Ako nisi nasao vrati odgovarajuci response
                    if (cartProduct == null)
                    {
                        return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                    }

                    // Skini za jedan sa racuna i koriguj cene u odnosu na to
                    cartProduct.Quantity--;
                    cartProduct.TotalPrice -= cartProduct.UnitPrice;

                    // Oduzmi od ukupnog za racun
                    cart.BillTotalPriceWithOutTax -= cartProduct.UnitPrice;
                    cart.BillTotalPriceWithTax = ((ConstantValues.Tax / 100) * cart.BillTotalPriceWithOutTax) + cart.BillTotalPriceWithOutTax;

                    // Ako je kolicina posle oduzimanja jednaka nula
                    if (cartProduct.Quantity == 0)
                    {
                        // Ukloni proizvod iz korpe
                        cartProducts.Remove(cartProduct);

                        // Ako je posle uklanjanja proizvoda korpa prazna
                        // vrati success false na osnovu kog ce view da refreshuje stranicu 
                        if (cartProducts.Count() == 0)
                        {
                            // Osvezi Session
                            Session["CartCounter"] = 0;
                            Session["CartProducts"] = new ShoppingCartViewModel();

                            return Json(new 
                            { 
                                success = false, 
                                counter = 0, 
                                total = "" 
                            }, JsonRequestBehavior.AllowGet);
                        }

                        // Osvezi Session
                        Session["CartProducts"] = cart;
                        Session["CartCounter"] = cart.CartProducts.Count;

                        // u suprotnom osvezi tabelu i ukupnu cenu
                        return Json(new 
                        { 
                            success = true, 
                            counter = cart.CartProducts.Count, 
                            total = cart.BillTotalPriceWithOutTax,
                            totalTax = cart.BillTotalPriceWithTax
                        }, JsonRequestBehavior.AllowGet);
                    }

                    // Osvezi Session
                    Session["CartProducts"] = cart;
                    Session["CartCounter"] = cart.CartProducts.Count;

                    // osvezi tabelu i ukupnu cenu
                    return Json(new 
                    { 
                        success = true, 
                        counter = cart.CartProducts.Count, 
                        total = cart.BillTotalPriceWithOutTax,
                        totalTax = cart.BillTotalPriceWithTax
                    }, JsonRequestBehavior.AllowGet);
                    
                }
            }

            // Ako nisi nista uradio vrati false
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        // POST: /Shopping/RemoveProduct/1
        [HttpPost]
        public ActionResult RemoveProduct(int id)
        {
            bool isCartEmpty = false; // da li je korpa prazna

            cart = Session["CartProducts"] as ShoppingCartViewModel;

            var product = cart.CartProducts.Single(x => x.ProductId == id);

FurnitureStore/Views/Shopping/ShoppingCart.cshtml
@using FurnitureStore.Models
@model FurnitureStore.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Korpa";
}

@Html.Partial("_PurchaseSuccess")

<div class="container border-primary my-3" id="content-wrapper" @*style="border:1px solid"*@>
    <hr />
    <h2 class="text-center page-title text-primary my-4">- Korpa -</h2>
    <hr />
    <table class="table table-bordered table-striped display nowarp w-100 bill-table mb-3">
        <thead class="thead-dark">
            <tr>
                <th class="text-center">Naziv proizvoda</th>
                <th class="text-center">Ime salona</th>
                <th class="text-center">Jedinična cena</th>
                <th></th>
                <th class="text-center">Količina</th>
                <th></th>
                <th class="text-center">Ukupno</th>
                <th class="text-center">Ukloni</th>
            </tr>
        </thead>
    </table>
    <div class="row">
        <div class="col">
            <hr />
            <h4 class="text-primary font-weight-bolder">
                Ukupna cena:
                @if (Model != null && Model.CartProducts.Any())
                {
                    <span class="font-weight-light" id="billTotalWithOutTax">
                        @Model.BillTotalPriceWithOutTax.ToString("#,##0.00 DIN")
                    </span>
                }
            </h4>
            <h4 class="text-primary font-weight-bolder">
                Porez:
                @if (Model != null && Model.CartProducts.Any())
                {                            
                    <span class="font-weight-light" id="tax">
                        @ConstantValues.Tax %
                    </span>
                }
            </h4>
            <h3 class="text-primary font-weight-bolder">
                Račun:                
                    @if (Model != null && Model.CartProducts.Any())
                    {
                        <span class="font-weight-light" id="billTotalWithTax">
                            @Model.BillTotalPriceWithTax.ToString("#,##0.00 DIN")
                        </span>
                    }
            </h3>
            <hr />
        </div>
    </div>
    @if (Model != null)
    {
        if (Model.CartProducts.Any())
        {
            <button class="btn btn-success mb-3 mx-auto d-block btn-buy" style="font-size: 1rem;letter-spacing:3px" onclick="buy()">Kupi</button>
        }
    }
</div>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css">

@section scripts
{
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script>
        let table;
        $(document).ready(function () {
            table = $(".bill-table").DataTable({
                ajax: {
                    url: "/Shopping/GetCartProducts",
                    method: "GET",
                    datatype: "json"
                },
                columns: [
                    { data: "ProductName", className: "dt-center" },
                    { data: "ShopName", className: "dt-center" },
                    {
                        data: "UnitPrice",
                        className: "dt-center",
                        render: function (data) {
                            var price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data);
                            return price;
                        }
                    },
                    {
                        data: "Add",
                        className: "dt-center",
                        render: function (data) {
                            return "<button class='btn-dark' style='font-size:1rem;width:30px;height:30px;'"
                                + "onclick=addToCart('@Url.Action("AddToCart", "Shopping")/" + data + "')>+</button>";
                        }
                    },
                    { data: "Quantity", className: "dt-center" },
                    {
                        data: "Remove",
                        className: "dt-center",
                        render: function (data) {
                            return "<button class='btn-dark' style='font-size:1rem;width:30px;height:30px;'"
                                + "onclick=removeFromCart('@Url.Action("RemoveFromCart", "Shopping")/" + data + "')>-</button>";
                        }
                    },
                    {
                        data: "TotalPrice",
                        className: "dt-center",
                        render: function (data) {
                            var price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data);
                            return price;
                        }
                    },
                    {
                        data: "ProductId",
                        className: "dt-center",
                        render: function (data) {
                            return "<button id='removeBtn' class='btn-dark'"
                                + "style='font-size:1rem;width:30px;height:30px;' data-product-id='" + data + "'"
                                + "onclick='removeProduct()'>&times;</button>"
                        }
                    }
                ],
                rowReorder: {
                    selector: 'td:nth-child(1)'
                },
                responsive: true,
                searching: false,
                paging: false,
                info: false,
                bSort: false,
                language: {
                    emptyTable: "<div style='font-weight: 500;'>Korpa je prazna</b></div>"
                },
            });
            $("#modalPurchased").on('hidden.bs.modal', function () {
                location.reload();
            })
        });
        function buy() {
            $.ajax({
                url: "/Shopping/Buy",
                method: "POST",
                success: function (data) {
                    if (data.success) {
                        $("#modalPurchased").modal("show");
                    }
                    else {
                        $.notify(data.messUrlge, {
                            globalPosition: "top center",
                            className: "error"
                        });
                    }
                }
            })
        }
        function addToCart(url) {
            $.ajax({
                url: url,
                method: "POST",
                success: function (data) {
                    if (data.success) {

                        table.ajax.reload();

                        // konvertuj cenu u odgovarajuci format
                        let price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.total);
                        let priceTax = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.totalTax);

                        $("#cartItem").text(data.counter);
                        $("#billTotalWithTax").text(priceTax); // ukupna cena za racun sa porezom
                        $("#billTotalWithOutTax").text(price); // ukupna cena za racun sa porezom
                    }
                    else {
                        // Ako nema na stanju vise obavesti korisnika
                        $.notify(data.message, {
                            globalPosition: "top center",
                            className: "error"
                        });
                    }
                }
            });
        }
        function removeFromCart(url) {
            $.ajax({
                url: url,
                method: "POST",
                success: function (data) {
                    if (data.success) {

                        table.ajax.reload();

                        // konvertuj cenu u odgovarajuci format
                        let price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.total);
                        let priceTax = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.totalTax);

                        $("#cartItem").text(data.counter); // broj proizvoda u korpi
                        $("#billTotalWithTax").text(priceTax); // ukupna cena za racun sa porezom
                        $("#billTotalWithOutTax").text(price); // ukupna cena za racun bez poreza
                    }
                    else {
                        table.ajax.reload(); // posto je korpa prazna reload-uj tabelu

                        $(".btn-buy").remove(); // posto je tabela prazna ukloni kupi dugme
                        $("#billTotalWithTax").remove(); // posto je tabela prazna ukloni cenu
                        $("#billTotalWithOutTax").remove();
                        $("#tax").remove();
                        $("#cartItem").text(data.counter); // vratice 0 pa ce counter biti 0 posto nema nista u korpi
                    }
                }
            });
        }
        function removeProduct() {
            let id = $("#removeBtn").attr("data-product-id");
            $.ajax({
                url: "/Shopping/RemoveProduct/" + id,
                method: "POST",
                success: function (data) {
                    if (data.success) {

                        table.ajax.reload();

                        // konvertuj cenu u odgovarajuci format
                        let price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.total);
                        let priceTax = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data.totalTax);

                        $("#cartItem").text(data.counter); // broj proizvoda u korpi
                        $("#billTotalWithTax").text(priceTax); // ukupna cena za racun sa porezom
                        $("#billTotalWithOutTax").text(price); // ukupna cena za racun bez poreza
                    }
                    if (data.isEmpty) {

                        $("#billTotalWithTax").remove(); // posto je tabela prazna ukloni cenu sa porezom
                        $("#billTotalWithOutTax").remove(); // posto je tabela prazna ukloni cenu bez poreza
                        $("#tax").remove(); // ukloni porez
                        $(".btn-buy").remove(); // posto je tabela prazna ukloni kupi dugme
                    }
                }
            })
        }
        function reloadPage() {
            location.reload(); // posto je kupovina uspesno obavljena osvezi stranicu
        }
    </script>
}

FurnitureStore/Views/Shopping/_PurchaseSuccess.cshtml
<div class="modal fade" tabindex="-1" id="modalPurchased">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Kupovina obavljena</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Proverite vaš e-mail, radi detalja o uplati novca.</p>
                <p>Da bi ste videli račun idite na vaš nalog.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="reloadPage()">Zatvori</button>
            </div>
        </div>
    </div>
</div>