FurnitureStore/Models/Product.cs
using FurnitureStore.CustomValidation;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace FurnitureStore.Models
{
    /// <summary>
    /// Predstavlja proizvod koji salon poseduje
    /// </summary>
    public class Product
    {
        #region Properties
        /// <summary>
        /// Primarni kljuc u tabeli za proizvod
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Sifra proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [StringLength(30, ErrorMessage = "Maksimalna dužina je 30 karaktera" )]
        [Display(Name = "Šifra proizvoda")]
        [Index(IsUnique = true)]
        public string ProductKey { get; set; }

        /// <summary>
        /// Naziv proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [StringLength(50, ErrorMessage = "Maksimalna dužina je 50 karaktera")]
        [Display(Name = "Naziv")]
        public string ProductName { get; set; }

        /// <summary>
        /// Zemlja proizvodnje proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [StringLength(100, ErrorMessage = "Maksimalna dužina je 100 karaktera")]
        [Display(Name = "Zemlja proizvodnje")]
        public string MadeIn { get; set; }

        /// <summary>
        /// Godina proizvodnje proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Godina proizvodnje")]
        public int ProductionYear { get; set; }

        /// <summary>
        /// Cena proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [Range(1, 1000000, ErrorMessage = "Minimalna cena je 1 maksimlana 1000000")]
        [Display(Name = "Cena")]
        public decimal Price { get; set; }

        /// <summary>
        /// Kolicina proizvoda u zalihama
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [Range(0, 500, ErrorMessage = "Minimalna količina je 0 maksimlana 500")]
        [Display(Name = "Količina")]
        public int Quantity { get; set; }

        /// <summary>
        /// Strani kljuc ka tabeli za salon namestaja
        /// </summary>
        [Display(Name = "Prodajni salon")]
        public int ShopId { get; set; }

        /// <summary>
        /// Strani kljuc ka tabeli za tip proizvoda
        /// </summary>
        [Display(Name = "Tip nameštaja")]
        public int ProductTypeId { get; set; }
        #endregion

        #region Navigation Properties
        /// <summary>
        /// Predstavlja salon namestaja koji poseduje dati proizvod
        /// </summary>
        public virtual Shop Shop { get; set; }

        /// <summary>
        /// Predstavlja tip proizvoda
        /// </summary>
        public virtual ProductType ProductType { get; set; }

        /// <summary>
        /// Predstavlja sliku proizvoda
        /// </summary>
        public virtual ICollection<UploadImage> UploadImages { get; set; }
        #endregion
    }
}

FurnitureStore/Models/ProductType.cs
using FurnitureStore.CustomValidation;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace FurnitureStore.Models
{
    /// <summary>
    /// Predstavlja tip proizvoda
    /// </summary>
    public class ProductType
    {
        #region Properties
        /// <summary>
        /// Primarni kljuc tabele za tip proizvoda
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Naziv tipa proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [StringLength(50, ErrorMessage = "Maksimalna dužina opisa je 500 karaktera")]
        [Display(Name = "Naziv")]
        [Index(IsUnique = true)]
        public string TypeName { get; set; }

        /// <summary>
        /// Opis tipa proizvoda
        /// </summary>
        [Required(ErrorMessage = "Polje je obavezno")]
        [StringLength(500, ErrorMessage = "Maksimalna dužina opisa je 500 karaktera")]
        [Display(Name = "Opis")]
        public string Description { get; set; }
        #endregion

        #region Navigation Properties
        /// <summary>
        /// Predstavlja vise komada proizvoda jednog tipa
        /// </summary>
        public virtual ICollection<Product> Products { get; set; }
        #endregion
    }
}

FurnitureStore/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FurnitureStore.ViewModels
{
    public class ProductViewModel
    {
        public string ProductName { get; set; }
        public string TypeName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
    }
}

FurnitureStore/Controllers/ProductsController.cs
using FurnitureStore.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using FurnitureStore.ViewModels;
using System.Web.UI.WebControls;
using System;
using System.IO;
using System.Collections.Generic;

namespace FurnitureStore.Controllers
{
    /// <summary>
    /// Kontroler za komade namestaja
    /// </summary>
    public class ProductsController : Controller
    {
        #region Konekcija ka bazi
        private readonly FurnitureStoreDbContext _context;
        public ProductsController()
        {
            _context = new FurnitureStoreDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        #endregion

        // GET: /Products
        #region Metoda za dobavljanje Index view-a komada namestaja
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.Admin))
            {
                return View();
            }
            return View("CustomerProductView");
        }
        #endregion

        // GET: /Products/GetProducts
        #region Metoda za dobavljanje podataka za tabelu komada namestaja
        [HttpGet]
        public ActionResult GetProducts()
        {

            var productsQuery = from u in _context.UploadImages.Include(x => x.Product).AsEnumerable()
                                select new
                                {
                                    Id = u.ProductId,
                                    ProductKey = u.Product.ProductKey,
                                    ProductName = u.Product.ProductName,
                                    MadeIn = u.Product.MadeIn,
                                    ProductionYear = u.Product.ProductionYear,
                                    Price = u.Product.Price,
                                    Quantity = u.Product.Quantity,
                                    ShopName = u.Product.Shop.ShopName,
                                    ProductTypeName = u.Product.ProductType.TypeName,
                                    Image = String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(u.ImageBytes))
                                };


            //var products = _context.Products.Include(x => x.Shop).Include(x => x.ProductType).ToList();

            //var images = _context.UploadImages.ToList();

            //var productsQuery = from p in products
            //                    from i in images
            //                    where p.Id == i.ProductId
            //                    select new
            //                    {
            //                        Id = p.Id,
            //                        ProductKey = p.ProductKey,
            //                        ProductName = p.ProductName,
            //                        MadeIn = p.MadeIn,
            //                        ProductionYear = p.ProductionYear,
            //                        Price = p.Price,
            //                        Quantity = p.Quantity,
            //                        ShopName = p.Shop.ShopName,
            //                        ProductTypeName = p.ProductType.TypeName,
            //                        Image = String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(i.ImageBytes))
            //                    };

            JsonResult result = Json(new { data = productsQuery }, JsonRequestBehavior.AllowGet);
            // Da bi mogao da vrati productQuery objekat koji ce biti veci od inicijalne MaxJsonLength koja je 2097152 karaktera ili 4MB
            // Namesteno na int max sto je 2147483647 da bi mogao sve podatke da vrati
            result.MaxJsonLength = int.MaxValue;

            return result;
        }
        #endregion

        // GET: /Products/AddOrEdit/1
        #region Metoda za dobavljanje ProductForm view-a za dodavanje ili izmenu komada namestaja 

        [HttpGet]
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult AddOrEdit(int id = 0)
        {
            #region popunjavanje liste za biranje godine
            var years = new List<string>();
            var date = DateTime.Now;
            int year = date.Year;

            for (int i = 0; i <= 10; i++)
            {
                years.Add(year.ToString());
                year--;
            }
            #endregion

            if (id == 0)
            {
                var product = new ProductFormViewModel
                {
                    ImageURL = "#",
                    Shops = _context.Shops.ToList(),
                    ProductTypes = _context.ProductTypes.ToList(),
                    Years = years
                };

                return View("ProductForm", product);
            }
            else
            {
                var productDb = _context.Products.SingleOrDefault(x => x.Id == id);
                var imageDb = _context.UploadImages.SingleOrDefault(x => x.ProductId == productDb.Id);

                var existingProduct = new ProductFormViewModel(productDb)
                {
                    ImageURL = String.Format("data:image/gif;base64,{0}", Convert.ToBase64String(imageDb.ImageBytes)),
                    Shops = _context.Shops.ToList(),
                    ProductTypes = _context.ProductTypes.ToList(),
                    Years = years
                };

                return View("ProductForm", existingProduct);
            }
        }
        #endregion

        // POST: /Products/AddOrEdit
        #region Metoda za dodavanje ili izmenu komada namestaja u bazi

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(ProductFormViewModel productFormVM)
        {            
            if (productFormVM.Id == 0)
            {
                if (!ModelState.IsValid)
                {
                    if (!ModelState.IsValidField("ProductionYear") && !ModelState.IsValidField("ProductKey"))
                    {
                        return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                    }
                    else if (!ModelState.IsValidField("ProductionYear"))
                    {
                        return Json(new { isYearNonValid = true }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { isKeyNonValid = true }, JsonRequestBehavior.AllowGet);
                    }
                }

                var newProduct = new Product
                {
                    Id = productFormVM.Id,
                    ProductKey = productFormVM.ProductKey,
                    ProductName = productFormVM.ProductName,
                    MadeIn = productFormVM.MadeIn,
                    ProductionYear = (int)productFormVM.ProductionYear,
                    Price = (int)productFormVM.Price,
                    Quantity = (int)productFormVM.Quantity,
                    ShopId = productFormVM.ShopId,
                    ProductTypeId = productFormVM.ProductTypeId
                };

                _context.Products.Add(newProduct);

                #region Dodavanje nove slike u bazu

                var newFile = productFormVM.Image;

                // Da bi dodali sliku u Images folder. Zakomentarisano da bi samo u bazu sacuvao
                //fileName.SaveAs(Server.MapPath("~/Images/") + Guid.NewGuid() + Path.GetExtension(fileName.FileName));

                string newFileName = Guid.NewGuid() + Path.GetExtension(newFile.FileName);

                byte[] imageBytes = null;

                BinaryReader reader = new BinaryReader(newFile.InputStream);
                imageBytes = reader.ReadBytes(newFile.ContentLength);

                UploadImage uploadImage = new UploadImage
                {
                    ProductId = newProduct.Id,
                    ImageBytes = imageBytes,
                    NewName = newFileName,
                    OldName = newFile.FileName,
                    ImagePath = "~/Images/" + newFileName
                };

                _context.UploadImages.Add(uploadImage);
                #endregion

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno sačuvano" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var productDb = _context.Products.SingleOrDefault(x => x.Id == productFormVM.Id);

                productDb.ProductKey = productFormVM.ProductKey;
                productDb.ProductName = productFormVM.ProductName;
                productDb.MadeIn = productFormVM.MadeIn;
                productDb.ProductionYear = (int)productFormVM.ProductionYear;
                productDb.Price = (decimal)productFormVM.Price;
                productDb.Quantity = (int)productFormVM.Quantity;
                productDb.ShopId = productFormVM.ShopId;
                productDb.ProductTypeId = productFormVM.ProductTypeId;

                #region Izmena postojece slike u bazi

                var modifiedFile = productFormVM.Image;

                // ako je izmenjena od strane klijenta izvrsi upis u bazu
                if (modifiedFile != null)
                {
                    var imageDb = _context.UploadImages.SingleOrDefault(x => x.ProductId == productFormVM.Id);
                    string newFileName = Guid.NewGuid() + Path.GetExtension(modifiedFile.FileName);

                    byte[] imageBytes = null;

                    BinaryReader reader = new BinaryReader(modifiedFile.InputStream);
                    imageBytes = reader.ReadBytes(modifiedFile.ContentLength);

                    imageDb.ImageBytes = imageBytes;
                    imageDb.NewName = newFileName;
                    imageDb.OldName = modifiedFile.FileName;
                    imageDb.ImagePath = "~/Images/" + newFileName;
                }
                #endregion

                _context.SaveChanges();

FurnitureStore/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Nameštaj";
}

<!--#region HTML za stranicu komada namestaja-->

<div class="container-fluid px-5 min-vh-100 bg-light position-relative pb-3">
    @Html.Partial("_SideNavbar")
    <hr />
    <h2 class="text-center page-title text-light bg-dark py-2">- Nameštaj -</h2>
    <hr />
    <div class="row">

        <div class="col">

            @Html.Partial("_ModalDelete")

            @Html.Partial("_ModalAddOrEdit")

            @Html.Partial("_ModalPopupImage")

            <!--#region Tabela za komade namestaja -->

            <button type="button" class="btn btn-success my-3 ml-auto d-block" data-toggle="modal"
                data-target="#modalAddOrEdit" onclick="popupForm('@Url.Action("AddOrEdit", "Products")')">
                <i class="fa fa-plus"></i> Dodaj nameštaj
            </button>

            <table id="productsTable" class="table display nowarp w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>Šifra</th>
                        <th>Naziv</th>
                        <th>Zemlja proizvodnje</th>
                        <th>Godina proizvodnje</th>
                        <th>Jedinična cena</th>
                        <th>Količina u magacinu</th>
                        <th>Prodajni salon</th>
                        <th>Tip</th>
                        <th>Slika</th>
                        <th>Akcije</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <!--#endregion -->

        </div>
    </div>
    <hr />
</div>
<!--#endregion -->

<!--#region CSS linkovi za DataTable  -->
@Styles.Render("~/Content/ImagePopup.css")
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css">
<!--#endregion -->


@section scripts
{
    <!--#region Skripte za validaciju, DataTable i notifikacije  -->
    @Scripts.Render("~/bundles/jqueryval");
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="~/Scripts/customValidation/customValidation.js"></script>
    <!--#endregion -->

    <!--#region Glavna skripta  -->

    <script>
        let table;
        $(document).ready(function () {

            //#region Dobavljanje podataka i popuna tabele za komade namestaja

            table = $("#productsTable").DataTable({
                ajax: {
                    url: "/Products/GetProducts",
                    type: "GET",
                    datatype: "json"
                },
                columns: [
                    { data: "ProductKey", className: "dt-center" },
                    { data: "ProductName", className: "dt-center table-primary" },
                    { data: "MadeIn", className: "dt-center" },
                    { data: "ProductionYear", className: "dt-center table-primary" },
                    {
                        data: "Price",
                        className: "dt-center",
                        render: function (data) {
                            let price = new Intl.NumberFormat("sr-RS", { style: "currency", currency: "DIN" }).format(data);
                            return price;
                        }
                    },
                    { data: "Quantity", className: "dt-center table-primary" },
                    { data: "ShopName", className: "dt-center" },
                    { data: "ProductTypeName", className: "dt-center table-primary" },
                    {
                        data: "Image",
                        className: "dt-center",
                        render: function (data) {
                            return "<img src='"+data+"' width='100px' height='100px' onclick=popupImage(this) style='cursor:pointer'/>";
                        },
                        orderable: false,
                        searchable: false,
                    },
                    {
                        data: "Id",
                        className: "dt-center table-primary",
                        render: function (data) {
                            return "<button type='button' class='btn btn-warning btn-sm m-1' data-toggle='modal' data-target='#modalAddOrEdit'"
                                + " onclick=popupForm('@Url.Action("AddOrEdit", "Products")/" + data + "')><i class='fas fa-pencil-alt'></i> Izmeni</button>"
                                + "<button type='button' class='btn btn-danger btn-sm m-1 btn-delete' data-toggle='modal' data-target='#modalDelete' onclick=confirmDelete("+data+")><i class='fa fa-trash'></i> Obriši</button> ";
                        },
                        orderable: false,
                        searchable: false,
                        width: "150px"
                    }
                ],
                language: {
                    emptyTable: "<div style='font-weight: 500;'>Tabela je prazna, klikni na <b>Dodaj nameštaj</b></div>",
                    "info": "Od _START_ do _END_ ukupno _TOTAL_",
                    "infoEmpty": "Od 0 do 0 ukupno 0",
                    "zeroRecords": "Traženi pojam ne postoji"
                },
                lengthMenu: [[3, 6, 9, -1], [3, 6, 9]],
                oLanguage: {
                    "oPaginate": {
                        "sNext": "Sledeća",
                        "sPrevious": "Prethodna"
                    },
                    "sProcessing": "Tabela je trenutno zauzeta",
                    "sLoadingRecords": "Učitavanje...",
                    "sLengthMenu": 'Prikaži <select>' +
                        '<option value="3">3</option>' +
                        '<option value="6">6</option>' +
                        '<option value="9">9</option>' +
                        '</select> proizvoda',
                    "sZeroRecords": "Nema traženih rezultata u pretrazi"
                },
                rowReorder: {
                    selector: 'td:nth-child(2)'
                },
                responsive: true,
                initComplete: function () {
                    // Apply the search
                    this.api().columns().every(function () {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that
                                    .search(this.value)
                                    .draw();
                            }
                        });
                    });
                },
                "dom": '<"top"l>rt<"bottom"ip><"clear">'
            });

            $('#productsTable tfoot th').each(function (index) {
                if (index == 1 || index == 2 || index == 3
                    || index == 4) {
                    var title = $(this).text();
                    $(this).html('<input type="text" placeholder="Pretraga" />');
                }
            });
            //#endregion

            //#region Izmena teksta u _ModalDelete modalu za potvrdu brisanja komada namestaja

            $("#modalDelete").on("shown.bs.modal", function () {
                $("#deleteTextContent").text("Da li ste sigurni da želite da obrišete komad nameštaja?");
            });
            //#endregion
        });

        //#region Metoda za dobavljanje i prikaz ProductForm view-a u body delu modala _ModalAddOrEdit

        function popupForm(url) {
            let formDiv = $("#modalAddOrEdit .modal-body");
            $.get(url)
                .done(function (response) {
                    let productId = $("#Id", response).val();
                    $("#mTitle").text((productId == 0) ? "Dodaj nameštaj" : "Izmeni nameštaj");
                    formDiv.html(response);

                    if (productId != 0) {
                        $("#productKey").attr("readonly", "readonly");
                    }
                });
        }

        //#endregion

        //#region Metoda za rest forme
        function resetForm() {
            $("form").trigger("reset");
        }
        //#endregion

        //#region Metoda za validaciju i slanje popunjene forme preko ajax post zahteva

        function submitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                let file = $("#btnImageBrowser").get(0).files;
                let formData = new FormData(form);
                formData.append("Image", file[0]);
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        if (data.success) {

                            $("#modalAddOrEdit").modal("hide");
                            table.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                        else if (data.isKeyNonValid) {
                            $("#productKeyGroup .field-validation-valid").text("Proizvod sa istom šifrom već postoji");
                            $("#productKeyGroup .field-validation-valid").css({ "color": "red" });
                            $("#productKey").toggleClass("input-validation-error");
                        }
                        else if (data.isYearNonValid) {
                            $("#yearGroup .field-validation-valid").text("Polje je obavezno");
                            $("#yearGroup .field-validation-valid").css({ "color": "red" });
                            $("#productionYear").toggleClass("input-validation-error");
                        }
                        else {
                            $("#productKeyGroup .field-validation-valid").text("Proizvod sa istom šifrom već postoji");
                            $("#productKeyGroup .field-validation-valid").css({ "color": "red" });
                            $("#productKey").toggleClass("input-validation-error");

                            $("#yearGroup .field-validation-valid").text("Polje je obavezno");
                            $("#yearGroup .field-validation-valid").css({ "color": "red" });
                            $("#productionYear").toggleClass("input-validation-error");
                        }
                    }
                });
            }
            return false;
        }
        //#endregion

        //#region Metoda za prikaz izabrane slike namestaja u modalnom prozoru

        function loadImage(input) {
            if (input.files && input.files[0]) {
                let reader = new FileReader();
                reader.onload = function (e) {
                    $("#targetImage").attr("src", e.target.result);
                };
                reader.readAsDataURL(input.files[0]);
                $("#targetImage").show();
            }
        }
        //#endregion

        //#region Metoda za potvrdu brisanja komada namestaja preko ajax post zahteva

        // na klik obrisi dugmeta na tabeli podesi atrribut data-item-id
        // na dugmetu modala na id koji je uzeo sa dugmeta tabele
        function confirmDelete(id) {
            $("#btn-confirm").attr("data-item-id", id);
        }

        // kada korisnik klikne na obrisi dugme na modalu
        // pokupi vrednost data-item-id od tog dugmeta 
        // i prosledi ga na url za ajax zahtev
        function executeDelete(btn) {
            let id = $(btn).attr("data-item-id");
            $.ajax({
                url: "/Products/Delete/" + id,
                method: "POST",
                success: function (data) {

                    table.ajax.reload();

                    $.notify(data.message, {
                        globalPosition: "top center",
                        className: "success"
                    });
                }
            });
        }
        //#endregion

        function popupImage(image) {
            let modal = $("#imageModal");
            let modalImg = $("#img-product");

            modal[0].style.display = "block";
            modalImg[0].src = $(image)[0].src;

            let span = $("#close-img");

            span.click(function () {
                modal[0].style.display = "none";
            });
        }
    </script>
    <!--#endregion -->
}