FurnitureStore/Controllers/ProductTypesController.cs
using FurnitureStore.Models;
using FurnitureStore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace FurnitureStore.Controllers
{
    /// <summary>
    /// Kontroler za kategoriju namestaja
    /// </summary>
    public class ProductTypesController : Controller
    {
        #region Konekcija ka bazi
        private readonly FurnitureStoreDbContext _context;
        public ProductTypesController()
        {
            _context = new FurnitureStoreDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        #endregion

        // GET: /ProductTypes
        #region Metoda za dobavljanje Index view-a kategorije namestaja
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.Admin))
            {
                return View();
            }
            return View("CustomerProductTypeView");
        }
        #endregion

        // GET: /ProductTypes/GetProductTypes
        #region Metoda za dobavljanje podataka za popunu tabele kategorije namestaja
        [HttpGet]
        public ActionResult GetProductTypes()
        {
            //List<ProductType> pt = new List<ProductType>();
            //for (int i = 0; i < 15000; i++)
            //{
            //    pt.Add(new ProductType
            //    {
            //        TypeName = "Name" + i,
            //        Description = "Description" + i
            //    });
            //}

            //_context.ProductTypes.AddRange(pt);
            //_context.SaveChanges();

            var productTypes = _context.ProductTypes.ToList();

            var productsQuery = from p in productTypes
                                select new
                                {
                                    Id = p.Id,
                                    TypeName = p.TypeName,
                                    Description = p.Description
                                };

            return Json(new { data = productsQuery }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        // GET: /ProductTypes/AddOrEdit/1
        #region Metoda za dobavljanje ProductTypeForm view-a za dodavanje ili izmenu kategorije namestaja

        [HttpGet]
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                var newProductType = new ProductTypeFormViewModel();

                return View("ProductTypeForm", newProductType);
            }
            else
            {
                var productTypeDb = _context.ProductTypes.SingleOrDefault(x => x.Id == id);

                var existingProductType = new ProductTypeFormViewModel(productTypeDb);

                return View("ProductTypeForm", existingProductType);
            }
        }
        #endregion

        // POST: /ProductTypes/AddOrEdit
        #region Metoda za dodavanje ili izmenu kategorije namestaja u bazi

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(ProductTypeFormViewModel productTypeFormVM)
        {
            
            if (productTypeFormVM.Id == 0)
            {
                if (!ModelState.IsValid)
                {
                    return Json(new { success = false }, JsonRequestBehavior.AllowGet);
                }

                var newProductType = new ProductType
                {
                    Id = productTypeFormVM.Id,
                    TypeName = productTypeFormVM.TypeName,
                    Description = productTypeFormVM.Description
                };

                _context.ProductTypes.Add(newProductType);

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno sačuvano" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var productTypeDb = _context.ProductTypes.SingleOrDefault(x => x.Id == productTypeFormVM.Id);

                productTypeDb.TypeName = productTypeFormVM.TypeName;
                productTypeDb.Description = productTypeFormVM.Description;

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno izmenjeno" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        // POST: /ProductTypes/Delete/1
        #region Metoda za brisanje kategorije namestaja iz baze

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var productTypeDb = _context.ProductTypes.FirstOrDefault(x => x.Id == id);
            _context.ProductTypes.Remove(productTypeDb);

            _context.SaveChanges();

            return Json(new { success = true, message = "Uspešno obrisano" }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Validacija
        [HttpPost]
        public ActionResult IsTypeNameAvailable(string TypeName)
        {
            try
            {
                var typeName = _context.ProductTypes.Single(x => x.TypeName == TypeName);
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion
    }
}

FurnitureStore/Views/ProductTypes/CustomerProductTypeView.cshtml
@{
    ViewBag.Title = "Kategorije nameštaja";
}

<!--#region HTML za stranicu kategorija namestaja-->
<div class="container-fluid px-5 min-vh-100 bg-light position-relative pb-3">
    @Html.Partial("_SideNavbar")
    <hr />
    <h2 class="text-center page-title text-light bg-dark py-2">- Kategorije nameštaja -</h2>
    <hr />
    <div class="row">
        <div class="col">

            <table id="productTypesTable" class="table display nowarp w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>Naziv</th>
                        <th>Opis</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <!--#endregion-->

        </div>
    </div>
    <hr />
</div>
<!--#endregion-->
<!--#region CSS linkovi za DataTable-->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css">
<!--#endregion-->

@section scripts
{
    <!--#region Skripte za validaciju, DataTable i notifikacije-->
    @Scripts.Render("~/bundles/jqueryval");
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
    <!--#endregion-->
    <!--#region Glavna skripta-->

    <script>
        let table;
        $(document).ready(function () {

            //#region Dobavljanje podataka i popuna tabele za kategoriju namestaja

            table = $("#productTypesTable").DataTable({
                ajax: {
                    url: "/ProductTypes/GetProductTypes",
                    type: "GET",
                    datatype: "json"
                },
                columns: [
                    { data: "TypeName", className: "dt-center" },
                    { data: "Description", className: "dt-center table-primary" },
                ],
                language: {
                    emptyTable: "<div style='font-weight: 500;'>Prodavnica trenutno ne poseduje nijednu kategoriju</div>",
                    "info": "Od _START_ do _END_ ukupno _TOTAL_",
                    "infoEmpty": "Od 0 do 0 ukupno 0",
                    "zeroRecords": "Traženi pojam ne postoji"
                },
                lengthMenu: [[3, 6, 9, -1], [3, 6, 9]],
                oLanguage: {
                    "oPaginate": {
                        "sNext": "Sledeća",
                        "sPrevious": "Prethodna"
                    },
                    "sProcessing": "Tabela je trenutno zauzeta",
                    "sLoadingRecords": "Učitavanje...",
                    "sLengthMenu": 'Prikaži <select>' +
                        '<option value="3">3</option>' +
                        '<option value="6">6</option>' +
                        '<option value="-1">9</option>' +
                        '</select> kategorija',
                    "sZeroRecords": "Nema traženih rezultata u pretrazi"
                },
                rowReorder: {
                    selector: 'td:nth-child(2)'
                },
                responsive: true,
                initComplete: function () {
                    // Apply the search
                    this.api().columns().every(function () {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that
                                    .search(this.value)
                                    .draw();
                            }
                        });
                    });
                },
                "dom": '<"top"l>rt<"bottom"ip><"clear">'
            });

            $('#productTypesTable tfoot th').each(function (index) {
                if (index == 0) {
                    var title = $(this).text();
                    $(this).html('<input type="text" placeholder="Pretraga" />');
                }
            });
            //#endregion
        });
    </script>
    <!--#endregion-->
}

FurnitureStore/Views/ProductTypes/Index.cshtml
@{
    ViewBag.Title = "Kategorije nameštaja";
}

<!--#region HTML za stranicu kategorija namestaja-->
<div class="container-fluid px-5 min-vh-100 bg-light position-relative pb-3">
    @Html.Partial("_SideNavbar")
    <hr />
    <h2 class="text-center page-title text-light bg-dark py-2">- Kategorije nameštaja -</h2>
    <hr />
    <div class="row">
        <div class="col">

            @Html.Partial("_ModalDelete")

            @Html.Partial("_ModalAddOrEdit")

            <!--#region Tabela za kategoriju namestaja-->
            <button type="button" class="btn btn-success my-3 d-block ml-auto" data-toggle="modal" data-target="#modalAddOrEdit" onclick="popupForm('@Url.Action("AddOrEdit", "ProductTypes")')"><i class="fa fa-plus"></i> Dodaj kategoriju</button>

            <table id="productTypesTable" class="table display nowarp w-100">
                <thead class="thead-dark">
                    <tr>
                        <th>Naziv</th>
                        <th>Opis</th>
                        <th>Akcije</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <!--#endregion-->

        </div>
    </div>
    <hr />
</div>
<!--#endregion-->

<!--#region CSS linkovi za DataTable-->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.7/css/rowReorder.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.7/css/responsive.dataTables.min.css">
<!--#endregion-->

@section scripts
{
    <!--#region Skripte za validaciju, DataTable i notifikacije-->
    @Scripts.Render("~/bundles/jqueryval");
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/rowreorder/1.2.7/js/dataTables.rowReorder.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdn.datatables.net/responsive/2.2.7/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <!--#endregion-->

    <!--#region Glavna skripta-->

    <script>
        let table;
        $(document).ready(function () {

            //#region Dobavljanje podataka i popuna tabele za kategoriju namestaja

            table = $("#productTypesTable").DataTable({
                ajax: {
                    url: "/ProductTypes/GetProductTypes",
                    type: "GET",
                    datatype: "json"
                },
                columns: [
                    { data: "TypeName", className: "dt-center" },
                    { data: "Description", className: "dt-center table-primary" },
                    {
                        data: "Id",
                        className: "dt-center",
                        render: function (data) {
                            return "<button type='button' class='btn btn-warning btn-sm m-1' data-toggle='modal' data-target='#modalAddOrEdit'"
                                + " onclick=popupForm('@Url.Action("AddOrEdit", "ProductTypes")/" + data + "')><i class='fas fa-pencil-alt'></i> Izmeni</button>"
                                + "<button type='button' class='btn btn-danger btn-sm m-1 btn-delete' data-toggle='modal' data-target='#modalDelete' onclick=confirmDelete("+data+")><i class='fa fa-trash'></i> Obriši</button> ";
                        },
                        orderable: false,
                        searchable: false,
                        width: "150px"
                    }
                ],
                language: {
                    emptyTable: "<div style='font-weight: 500;'>Tabela je prazna, klikni na <b>Dodaj kategoriju</b></div>",
                    "info": "Od _START_ do _END_ ukupno _TOTAL_",
                    "infoEmpty": "Od 0 do 0 ukupno 0",
                    "zeroRecords": "Traženi pojam ne postoji"
                },
                lengthMenu: [[3, 6, 9, -1], [3, 6, 9]],
                oLanguage: {
                    "oPaginate": {
                        "sNext": "Sledeća",
                        "sPrevious": "Prethodna"
                    },
                    "sProcessing": "Tabela je trenutno zauzeta",
                    "sLoadingRecords": "Učitavanje...",
                    "sLengthMenu": 'Prikaži <select>' +
                        '<option value="3">3</option>' +
                        '<option value="6">6</option>' +
                        '<option value="9">9</option>' +
                        '</select> kategorija',
                    "sZeroRecords": "Nema traženih rezultata u pretrazi"
                },
                rowReorder: {
                    selector: 'td:nth-child(2)'
                },
                responsive: true,
                initComplete: function () {
                    // Apply the search
                    this.api().columns().every(function () {
                        var that = this;

                        $('input', this.footer()).on('keyup change clear', function () {
                            if (that.search() !== this.value) {
                                that
                                    .search(this.value)
                                    .draw();
                            }
                        });
                    });
                },
                "dom": '<"top"l>rt<"bottom"ip><"clear">'
            });

            $('#productTypesTable tfoot th').each(function (index) {
                if (index == 0) {
                    var title = $(this).text();
                    $(this).html('<input type="text" placeholder="Pretraga" />');
                }
            });
            //#endregion

            //#region Izmena teksta u _ModalDelete modalu za potvrdu brisanja kategorije namestaja

            $("#modalDelete").on("shown.bs.modal", function () {
                $("#deleteTextContent").text("Da li ste sigurni da želite da obrišete kategoriju?");
            });
            //#endregion
        });

        //#region Metoda za dobavljanje i prikaz ProductTypeForm view-a u body delu modala _ModalAddOrEdit

        function popupForm(url) {
            let formDiv = $("#modalAddOrEdit .modal-body");
            $.get(url)
                .done(function (response) {
                    let productTypeId = $("#Id", response).val();
                    $("#mTitle").text((productTypeId == 0) ? "Dodaj kategoriju" : "Izmeni kategoriju");
                    formDiv.html(response);

                    if (productTypeId != 0) {
                        $("#typeName").attr("readonly", "readonly");
                    }
                });
        }
        //#endregion

        //#region Metoda za validaciju i slanje popunjene forme preko ajax post zahteva

        function submitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {

                            $("#modalAddOrEdit").modal("hide");
                            table.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                        else {
                            $("#typeNameGroup .field-validation-valid").text("Kategorija sa istim nazivom već postoji");
                            $("#typeNameGroup .field-validation-valid").css({ "color": "red" });
                            $("#typeName").toggleClass("input-validation-error");
                        }
                    }
                })
            }
            return false;
        }
        //#endregion

        //#region Metoda za potvrdu brisanja kategorije namestaja preko ajax post zahteva

        // na kilk obrisi dugmeta na tabeli podesi atrribut data-item-id
        // na dugmetu modala na id koji je uzeo sa dugmeta tabele
        function confirmDelete(id) {
            $("#btn-confirm").attr("data-item-id", id);
        }

        // kada korisnik klikne na obrisi dugme na modalu
        // pokupi vrednost data-item-id od tog dugmeta 
        // i prosledi ga na url za ajax zahtev
        function executeDelete(btn) {
            let id = $(btn).attr("data-item-id");
            $.ajax({
                url: "/ProductTypes/Delete/" + id,
                method: "POST",
                success: function (data) {

                    table.ajax.reload();

                    $.notify(data.message, {
                        globalPosition: "top center",
                        className: "success"
                    });
                }
            });
        }
        //#endregion
    </script>
    <!--#endregion-->
}

FurnitureStore/Views/ProductTypes/ProductTypeForm.cshtml
@model FurnitureStore.ViewModels.ProductTypeFormViewModel
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "ProductTypes", FormMethod.Post, new { onsubmit = "return submitForm(this)" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()
    <div class="form-group" id="typeNameGroup">
        @Html.LabelFor(model => model.TypeName, new { @class = "control-label" })
        @Html.EditorFor(model => model.TypeName, new { htmlAttributes = new { @class = "form-control", @id = "typeName", placeholder = "Naziv kategorije" } })
        @Html.ValidationMessageFor(model => model.TypeName)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
        @Html.TextAreaFor(model => model.Description, htmlAttributes: new { @class = "form-control", size = "5", @id = "description", placeholder = "Opis kategorije" } )
        @Html.ValidationMessageFor(model => model.Description)
    </div>
    <hr />
    <div class="form-group d-flex justify-content-around mt-4">
        <input type="submit" class="btn btn-success" value="Sačuvaj" />
        <input type="reset" class="btn btn-outline-secondary" value="Poništi" />
    </div>
}