FurnitureStore/Controllers/BillsController.cs
using FurnitureStore.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using FurnitureStore.ViewModels;

namespace FurnitureStore.Controllers
{
    public class BillsController : Controller
    {
        #region Konekcija ka bazi
        private readonly FurnitureStoreDbContext _context;
        public BillsController()
        {
            _context = new FurnitureStoreDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        #endregion

        // GET: Bills
        [HttpGet]
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult GetBills()
        {
            var query = from b in _context.Bills.Include(x => x.ShoppingCartProducts)
                        select new
                        {
                            Customer = b.User.Name + " " + b.User.Surname,
                            PurchaseDate = b.PurchaseDate,
                            TotalPrice = b.TotalPrice,
                            PurchasedProducts = b.ShoppingCartProducts
                        };

            return Json(new { data = query, success = true }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetBill(int id)
        {
            var billDb = _context.Bills.Include(x => x.ShoppingCartProducts).SingleOrDefault(x => x.Id == id);

            var userBill = new UserBillViewModel
            {
                PurchasedProducts = billDb.ShoppingCartProducts,
                Tax = billDb.Tax,
                PurchaseDate = billDb.PurchaseDate,
                TotalPrice = billDb.TotalPrice
            };

            return View("_UserBill", userBill);
        }
    }
}

FurnitureStore/Controllers/ShopsController.cs
using FurnitureStore.Models;
using FurnitureStore.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;

namespace FurnitureStore.Controllers
{
    /// <summary>
    /// Kontroler za salone namestaja
    /// </summary>
    public class ShopsController : Controller
    {
        #region Konekcija ka bazi

        private readonly FurnitureStoreDbContext _context;
        public ShopsController()
        {
            _context = new FurnitureStoreDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        #endregion

        // GET: /Shops
        #region Metoda za dobavljanje Index view-a za salone namestaja
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.Admin))
            {
                return View();
            }
            return View("CustomerShopView");
        }
        #endregion

        // GET: /Shops/GetShops
        #region Metoda za dobavljanje podataka za tabelu salona namestaja
        [HttpGet]
        public ActionResult GetShops()
        {
            var shops = _context.Shops.ToList();
            var addresses = _context.Addresses.ToList();

            var shopsQuery = from s in shops
                             from a in addresses
                             where s.Id == a.ShopId
                             select new
                             {
                                 Id = s.Id,
                                 ShopName = s.ShopName,
                                 Address = a.StreetName + " " + a.StreetNumber + " " + a.City,
                                 OwnerName = s.OwnerName,
                                 PhoneNumber = s.PhoneNumber,
                                 Email = s.Email,
                                 WebPageURL = s.WebPageURL,
                                 PIB = s.PIB,
                                 BZR = s.BZR
                             };

            return Json(new { data = shopsQuery }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        // GET: /Shops/AddOrEdit/1
        #region Metoda za dobavljanje ShopForm view-a za dodavanje ili izmenu salona namestaja

        [HttpGet]
        [Authorize(Roles = RoleName.Admin)]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                var shop = new ShopFormViewModel
                {
                    Address = new AddressViewModel()
                };

                return View("ShopForm", shop);
            }
            else
            {
                var shopDb = _context.Shops.SingleOrDefault(x => x.Id == id);
                var addressDb = _context.Addresses.SingleOrDefault(x => x.ShopId == shopDb.Id);

                var existingShop = new ShopFormViewModel(shopDb)
                {
                    Address = new AddressViewModel(addressDb)
                };

                return View("ShopForm", existingShop);
            }
        }
        #endregion

        // POST: /Shops/AddOrEdit
        #region Metoda za dodavanje ili izmenu salona u bazi

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(ShopFormViewModel shopFormVM)
        {
            if (shopFormVM.Id == 0)
            {
                if (!ModelState.IsValid)
                {
                    // Za validaciju - ako prilikom submita nisu prosledjena validna unique polja ModelState nece biti validan
                    // i vratice na view json sa odgovarajucim podacima
                    if (!ModelState.IsValidField("BZR") && !ModelState.IsValidField("PIB"))
                    {
                        return Json(new { success = false, prop = "" }, JsonRequestBehavior.AllowGet);
                    }
                    else if (!ModelState.IsValidField("BZR"))
                    {
                        return Json(new { success = false, prop = "bzr" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(new { success = false, prop = "pib" }, JsonRequestBehavior.AllowGet);
                    }
                }

                var newShop = new Shop
                {
                    Id = shopFormVM.Id,
                    ShopName = shopFormVM.ShopName,
                    OwnerName = shopFormVM.OwnerName,
                    PhoneNumber = shopFormVM.PhoneNumber,
                    Email = shopFormVM.Email,
                    WebPageURL = shopFormVM.WebPageURL,
                    BZR = shopFormVM.BZR,
                    PIB = (int)shopFormVM.PIB
                };

                _context.Shops.Add(newShop);

                var newAddress = new Address
                {
                    Id = shopFormVM.Id,
                    StreetName = shopFormVM.Address.StreetName,
                    StreetNumber = shopFormVM.Address.StreetNumber,
                    ZipCode = (int)shopFormVM.Address.ZipCode,
                    City = shopFormVM.Address.City,
                    ShopId = shopFormVM.Id
                };

                _context.Addresses.Add(newAddress);

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno sačuvano" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var shopDb = _context.Shops.SingleOrDefault(x => x.Id == shopFormVM.Id);

                shopDb.ShopName = shopFormVM.ShopName;
                shopDb.OwnerName = shopFormVM.OwnerName;
                shopDb.PhoneNumber = shopFormVM.PhoneNumber;
                shopDb.Email = shopFormVM.Email;
                shopDb.WebPageURL = shopFormVM.WebPageURL;
                shopDb.BZR = shopFormVM.BZR;
                shopDb.PIB = (int)shopFormVM.PIB;

                var addressDb = _context.Addresses.SingleOrDefault(x => x.ShopId == shopDb.Id);

                addressDb.StreetName = shopFormVM.Address.StreetName;
                addressDb.StreetNumber = shopFormVM.Address.StreetNumber;
                addressDb.ZipCode = (int)shopFormVM.Address.ZipCode;
                addressDb.City = shopFormVM.Address.City;
                addressDb.ShopId = shopFormVM.Id;

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno izmenjeno" }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        // POST: /Shops/Delete/1
        #region Metoda za brisanje salona namestaja

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var shopDb = _context.Shops.FirstOrDefault(x => x.Id == id);
            _context.Shops.Remove(shopDb);

            _context.SaveChanges();

            return Json(new { success = true, message = "Uspešno obrisano" }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

FurnitureStore/Controllers/UsersController.cs
using FurnitureStore.Models;
using FurnitureStore.ViewModels;
using System.Web.Mvc;
using System.Data.Entity;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace FurnitureStore.Controllers
{
    // Da bi zabranili ulogovanom korisniku koji nije admin
    // pristup stranici preko url-a
    [Authorize(Roles = RoleName.Admin)]
    public class UsersController : Controller
    {
        private readonly FurnitureStoreDbContext _context;
        public UsersController()
        {
            _context = new FurnitureStoreDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetUsers()
        {
            var users = _context.Users.Include(u => u.Roles).ToList();
            var adresses = _context.Addresses.ToList();

            var usersQuery = from u in users
                             from a in adresses
                             where u.Id == a.UserId
                             select new
                             {
                                 Id = u.Id,
                                 Username = u.UserName,
                                 Name = u.Name,
                                 Surname = u.Surname,
                                 Email = u.Email,
                                 Address = a.StreetName + " " + a.StreetNumber + " " + a.City,
                                 Role = (from rol in _context.Roles
                                         from usr in rol.Users
                                         where usr.UserId == u.Id
                                         select rol).First().Name
                                 // Iz navigacijskog propertija ICollection<IdentityUserRoles>
                                 // iz tabele IdentityRoles proveri da li se u toj tabeli
                                 // nalazi kljuc trenutno selektovanog korisnika, ako se kljuc
                                 // nalazi u navigacijskom propertiju selektuj ime uloge(Name)
                             };


            return Json(new { data = usersQuery }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddOrEdit(string id)
        {
            if (id == null)
            {
                var userRolesDb = _context.Roles.ToList();
                var userRoles = new List<UserRoleViewModel>();

                foreach (var role in userRolesDb)
                {
                    userRoles.Add(new UserRoleViewModel(role.Id, role.Name));
                }

                var newUser = new UserFormViewModel()
                {
                    UserRoles = userRoles,
                    Address = new AddressViewModel()
                };

                return View("UserForm", newUser);
            }
            else
            {
                var userDb = _context.Users.FirstOrDefault(x => x.Id == id);
                var addressDb = _context.Addresses.FirstOrDefault(x => x.UserId == userDb.Id);

                var userRolesDb = _context.Roles.ToList();

                var userRoles = new List<UserRoleViewModel>();

                foreach (var role in userRolesDb)
                {
                    userRoles.Add(new UserRoleViewModel(role.Id, role.Name));
                }

                var existingUser = new UserFormViewModel()
                {
                    Id = userDb.Id,
                    Username = userDb.UserName,
                    Name = userDb.Name,
                    Surname = userDb.Surname,
                    Email = userDb.Email,
                    UserRoleId = (from rol in _context.Roles
                                  from usr in rol.Users
                                  where usr.UserId == userDb.Id
                                  select rol).First().Id,
                    UserRoles = userRoles,
                    Address = new AddressViewModel(addressDb)
                };

                return View("EditUserForm", existingUser);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrEdit(UserFormViewModel userFormVM)
        {
            if (userFormVM.Id == null)
            {
                var newUser = new User
                {
                    UserName = userFormVM.Username,
                    Name = userFormVM.Name,
                    Surname = userFormVM.Surname,
                    Email = userFormVM.Email
                };

                // Dodaj novog korisnika
                var userManager = new UserManager<User>(new UserStore<User>(_context));
                var result = userManager.Create(newUser, userFormVM.Password);

                // Ako je korisnik uspesno dodat
                if (result.Succeeded)
                {
                    // Dodeli korisniku izabranu ulogu
                    userManager.AddToRole(newUser.Id, _context.Roles.SingleOrDefault(x => x.Id == userFormVM.UserRoleId).Name);

                    var newAddress = new Address
                    {
                        StreetName = userFormVM.Address.StreetName,
                        StreetNumber = userFormVM.Address.StreetNumber,
                        ZipCode = (int)userFormVM.Address.ZipCode,
                        City = userFormVM.Address.City,
                        UserId = newUser.Id
                    };

                    _context.Addresses.Add(newAddress);

                    var userRole = new IdentityUserRole
                    {
                        UserId = newUser.Id,
                        RoleId = userFormVM.UserRoleId
                    };

                    _context.SaveChanges();
                }              

                return Json(new { success = true, message = "Uspešno sačuvano" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var userDb = _context.Users.SingleOrDefault(x => x.Id == userFormVM.Id);

                userDb.Name = userFormVM.Name;
                userDb.Surname = userFormVM.Surname;
                userDb.Email = userFormVM.Email;

                var addressDb = _context.Addresses.SingleOrDefault(x => x.UserId == userDb.Id);

                addressDb.StreetName = userFormVM.Address.StreetName;
                addressDb.StreetNumber = userFormVM.Address.StreetNumber;
                addressDb.ZipCode = (int)userFormVM.Address.ZipCode;
                addressDb.City = userFormVM.Address.City;

                // Dodavanje nove uloge korisniku
                var userManager = new UserManager<User>(new UserStore<User>(_context));

                // Posto ne znamo da li je korisniku promenjena uloga prvo moramo da
                // dobavimo iz baze njegovu trenutnu ulogu
                var oldRole = (from rol in _context.Roles
                               from usr in rol.Users
                               where usr.UserId == userDb.Id
                               select rol).First();

                // Ukloni korisnika sa trenutne uloge
                userManager.RemoveFromRole(userDb.Id, oldRole.Name);
                // Dodeli mu novu ulogu
                userManager.AddToRole(userDb.Id, _context.Roles.Single(x => x.Id == userFormVM.UserRoleId).Name);

                _context.SaveChanges();

                return Json(new { success = true, message = "Uspešno izmenjeno" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Delete(string id)
        {
            var userManager = new UserManager<User>(new UserStore<User>(_context));
            var userDb = _context.Users.FirstOrDefault(x => x.Id == id);

            var billDb = _context.Bills.FirstOrDefault(x => x.UserId == userDb.Id);

            // Proveri da li korisnik ima racuna, ako nema izbrisi samo korisnika
            // jer ako je racun null bacice exception
            if (billDb != null)
            {
                _context.Bills.Remove(billDb);
            }

            _context.SaveChanges();

            userManager.Delete(userDb);

            return Json(new { success = true, message = "Uspešno obrisano", JsonRequestBehavior.AllowGet });
        }
    }
}

FurnitureStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SOFA</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="text-primary bg-light">
    @Html.Partial("_NavBar")
    <main class="container-fluid p-0 border-0 position-relative">
        @RenderBody()
    </main>
    <footer class="fixed-bottom text-center bg-primary">
        <p class="text-white m-0">&copy; @DateTime.Now.Year - Sofa</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        //#region Skripta za SideNavbar
        $(document).ready(function () {
            $("#menu-toggle").click(function (e) {
                e.preventDefault();
                $("#wrapper").toggleClass("toggled");
                $("#btn-close").attr("hidden", false);
            });
            $("#btn-close").click(function () {
                $("#wrapper").toggleClass("toggled");
                $("#btn-close").attr("hidden", true);
            })
        });
        //#endregion
    </script>
</body>
</html>

FurnitureStore/Views/Shared/_ModalAddOrEdit.cshtml
<div class="modal fade" id="modalAddOrEdit" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content bg-light">
            <div class="modal-header">
                <h5 class="modal-title" id="mTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>

FurnitureStore/Views/Shared/_ModalDelete.cshtml
<div class="modal fade" id="modalDelete">
    <div class="modal-dialog">
        <div class="modal-content bg-light">
            <div class="modal-header">
                <h5 class="modal-title">Obriši</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p id="deleteTextContent" class='my-3'></p>
            </div>
            <div class="modal-footer d-flex justify-content-around flex-wrap">
                <button type="button" id="btn-confirm" data-item-id="" class="btn btn-danger" data-dismiss="modal" onclick="executeDelete(this)">Obriši</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Zatvori</button>
            </div>
        </div>
    </div>
</div>

FurnitureStore/Views/Shared/_ModalPopupImage.cshtml
<div id="imageModal" class="modal">    

    <!-- Modal Content (The Image) -->
    <div id="img-wrapper">
        <!-- The Close Button -->
        <span id="close-img">&times;</span>
        <img id="img-product">
    </div>

    <!-- Modal Caption (Image Text) -->
    <div id="caption"></div>
</div>

FurnitureStore/Views/Shared/_ShoppingCart.cshtml
<li class="d-flex align-items-center">
    <a class="nav-link" href="/Shopping/ShoppingCart">
        <div class="navbar-icon-cart d-flex align-items-center">
            <svg fill="#fff" height="30px" viewBox="0 -31 512.00026 512" width="30px" xmlns="http://www.w3.org/2000/svg"><path d="m164.960938 300.003906h.023437c.019531 0 .039063-.003906.058594-.003906h271.957031c6.695312 0 12.582031-4.441406 14.421875-10.878906l60-210c1.292969-4.527344.386719-9.394532-2.445313-13.152344-2.835937-3.757812-7.269531-5.96875-11.976562-5.96875h-366.632812l-10.722657-48.253906c-1.527343-6.863282-7.613281-11.746094-14.644531-11.746094h-90c-8.285156 0-15 6.714844-15 15s6.714844 15 15 15h77.96875c1.898438 8.550781 51.3125 230.917969 54.15625 243.710938-15.941406 6.929687-27.125 22.824218-27.125 41.289062 0 24.8125 20.1875 45 45 45h272c8.285156 0 15-6.714844 15-15s-6.714844-15-15-15h-272c-8.269531 0-15-6.730469-15-15 0-8.257812 6.707031-14.976562 14.960938-14.996094zm312.152343-210.003906-51.429687 180h-248.652344l-40-180zm0 0" /><path d="m150 405c0 24.8125 20.1875 45 45 45s45-20.1875 45-45-20.1875-45-45-45-45 20.1875-45 45zm45-15c8.269531 0 15 6.730469 15 15s-6.730469 15-15 15-15-6.730469-15-15 6.730469-15 15-15zm0 0" /><path d="m362 405c0 24.8125 20.1875 45 45 45s45-20.1875 45-45-20.1875-45-45-45-45 20.1875-45 45zm45-15c8.269531 0 15 6.730469 15 15s-6.730469 15-15 15-15-6.730469-15-15 6.730469-15 15-15zm0 0" /></svg>
            <div class="navbar-cart-badge text-center text-white" id="cartItem">@Session["CartCounter"]</div>
        </div>
    </a>
</li>

FurnitureStore/Views/Shared/_SideNavbar.cshtml
@using FurnitureStore.Models

<div class="pb-3" id="wrapper">
    <div class="text-white bg-primary" id="sidebar-wrapper">
        <div id="btn-close">&times;</div>
        <h2 class="sidebar-heading">MENI</h2>
        <div class="list-group list-group-flush">
            @Html.ActionLink("Saloni", "Index", "Shops", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })
            @Html.ActionLink("Kategorije", "Index", "ProductTypes", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })
            @Html.ActionLink("Nameštaj", "Index", "Products", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })

            @*Ako je korisnik u ulozi admina prikazi linkove u if bloku*@
            @if (ViewContext.HttpContext.User.IsInRole(RoleName.Admin))
            {
                @Html.ActionLink("Korisnici", "Index", "Users", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })
                @Html.ActionLink("Računi", "Index", "Bills", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })
                @Html.ActionLink("Izveštaj", "Index", "ProfitReport", null, new { @class = "list-group-item list-group-item-action bg-dark font-weight-normal text-white" })
            }
        </div>
    </div>
</div>

<button class="btn btn-secondary align-self-start my-3" id="menu-toggle">MENI</button>